name: lab_manajemen_sekolah
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  uuid: ^3.0.7
  file_picker: ^5.5.0
  camera_camera: ^3.0.0
  image_cropper: ^5.0.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.3.0
  permission_handler: ^11.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/labmase.png"
